version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - 'echo Installing dependencies...'
      - 'node --version'
      - 'npm --version'
      - 'npm install'
      - 'npm install -g prisma'

  pre_build:
    commands:
      - 'echo Running prisma generate...'
      - 'npx prisma generate'
      - 'echo Running linting...'
      - 'npm run lint || echo "Linting warnings ignored"'

  build:
    commands:
      - 'echo Building the application...'
      - 'npm run build'

  post_build:
    commands:
      - 'echo Build completed on `date`'
      - 'echo Creating deployment package...'
      - 'mkdir -p node_modules/.prisma/client'
      # Bundle node_modules
      - 'cp -R node_modules .ebextensions .platform prisma dist package.json package-lock.json Procfile .npmrc $CODEBUILD_SRC_DIR/'

artifacts:
  files:
    - 'node_modules/**/*'
    - 'dist/**/*'
    - 'prisma/**/*'
    - '.platform/**/*'
    - '.ebextensions/**/*'
    - 'package.json'
    - 'package-lock.json'
    - 'Procfile'
    - '.npmrc'
  base-directory: '.'
  discard-paths: no

cache:
  paths:
    - 'node_modules/**/*'
