version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - 'echo Installing dependencies for build...'
      - 'node --version'
      - 'npm --version'
      - 'echo Checking system compatibility...'
      - 'ldd --version | head -n 1 || true'
      - 'pwd'
      - 'ls -la'
      - 'echo DEBUG: Parent directory structure'
      - 'ls -la ..'
      - 'echo DEBUG: Root directory structure'
      - 'ls -la /'
      - 'echo Continuing with installation...'
      - 'npm install'

  pre_build:
    commands:
      - 'echo Preparing build environment...'
      - 'echo Build started at `date`'

  build:
    commands:
      - 'echo Building the application...'
      - 'npm run build'
      - 'echo Preparing package for Elastic Beanstalk...'
      - 'mkdir -p .ebextensions .platform'
      - 'cp -r .ebextensions .platform dist/'
      - 'cp package.json package-lock.json Procfile .env.example dist/'
      - 'cd dist && npm install --production && cd ..'

  post_build:
    commands:
      - 'echo Build completed at `date`'
      - 'echo Packaging complete'

artifacts:
  files:
    - 'dist/**/*'
    - '.ebextensions/**/*'
    - '.platform/**/*'
    - 'package.json'
    - 'package-lock.json'
    - 'Procfile'
    - '.env.example'
  base-directory: '.'
  discard-paths: no

cache:
  paths:
    - 'node_modules/**/*'
