version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm ci

  build:
    commands:
      - npm run build
      - npm run lint
      - npx prisma generate

artifacts:
  files:
    - 'dist/**/*'
    - 'node_modules/**/*'
    - 'prisma/**/*'
    - 'package.json'
    - 'package-lock.json'
    - 'tsconfig.json'
    - '.env*'
  base-directory: '.'
  discard-paths: no

cache:
  paths:
    - 'node_modules/**/*'
